### ISSUE TITLE
Score tracker

### ISSUE THREAD

**Issue by WangHexie** [WangHexie/chinese_adversarial_samples#1]
- [x] replace (10) self-defined dirty word: 24.5441
- [x] replace (4) self-defined dirty word: 23.8000
- [x] replace dirty characater with full pinyin:  4.4628
- [x] replace dirty characater with start character of pinyin: 56.8371    `[2]`
- [x]  randomly insert punctuation into dirty words(length in (2, 3)):  27.3687    `[3]`
- [x] `[2]`+ `[3]`: 56.9101
- [x] delete dirty character found in `2,3`: 179.4251
- [x] delete dirty character found in `2,3` , min_df=0.0005, character 70,  word 1000, classifier 0.1: 195.92
- [x] delete dirty character found in `2,3` , min_df=0.0002, character 70,  word 1000, classifier 0.1 + online mining: 282.47  `[4]`
- [x] delete dirty character found + tokenizer+ all at a time + low min_df threshold+ online mining: 320.44
- [x] replace with shape_like_or_sound_like_word for the dirty character found + tokenizer+ all at a time + low min_df threshold+ online mining: 173.8214 
- [x] replace with sound_like common word for the dirty character found + tokenizer+ all at a time + low min_df threshold+ online mining:142.8442
- [x] replace with sound_like common word for the dirty character found + tokenizer+ all at a time + low min_df threshold+ online mining+5000 word:143.9313
- [x] replace with embedding similar word for the dirty character found + tokenizer+ all at a time + low min_df threshold+ online mining+5000 word:192.7456
- [x]  full pinyin in 2 `2,3` , min_df=0.0005, character 70,  word 1000, classifier 0.1 + online mining: 9.3168
- [x]  full pinyin in 2 `2,3` , min_df=0.0005, character 70,  word 1000, classifier 0.1 + online mining+ random uppercase: 8.7713
- [x]  `2,3` , min_df=0.0005, character 70,  word 1000, classifier 0.1 + online mining: 61.4206
- [x] `[2]`+ `[3]` online mining:   3.1843 `(bug:split)`
- [x] `[2]`+ `[3]` online mining + self data:   5.4697 `(bug:split)`

-------------------------------------------
- [x] randomly shuffle the sentences: 28.4789/41.0211 (character level)
----------------------------------------------------------
- [x] append good words in sentences: 10.1973 `(bug:append bad word)`
- [x] append good words in sentences, 0.5 percent: 23.9289
------------------------------------------------------
- [x] sota paper attack 5 word, 0.4 threshold: 46.5476
- [x] sota paper num_of_synonyms=50,
                                        threshold_of_stopping_attack=0.1, tokenize_method=1, text_modify_percentage=0.55: 27.5697
- [x] sota paper attack 5 word, 0.1 threshold: 54.2324  `(bug:not using threshold)`
- [x] sota paper attack 6 word, 0.02 threshold, num_of_synonyms=8, word tokenize: 57.1827 `(bug:not using threshold)`
- [x] sota paper attack 6 word, 0.02 threshold, num_of_synonyms=8, word tokenize, tencent embedding, (self-trained fasttext +  `[4]`)multiple classifier emsembled:44.1952 `(bug:not using threshold)`
- [x] sota paper attack 6 word, 0.08 threshold + `[2]`:   78.56 `(bug:not using threshold)`
- [x] sota paper tfidf , replace with similar-sound word, 0.1 threshold: 91.4464
- [x] sota paper tfidf , replace with similar-sound word, 0.001 threshold: 95.9487
- [x] sota paper tfidf+fasttext , replace with similar-sound word, 0.1 threshold: 98.6706
- [x] sota paper tfidf(full tokenizer) , replace with similar word, 0.001 threshold: 155.2444 `[5]`
- [x] `[5]` + threshold_of_stopping_attack=0.2 :125.7031
- [x] `[5]` + threshold_of_stopping_attack=0.0000001: 155.2142
