### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by WangHexie** [WangHexie/chinese_adversarial_samples#3]
- [x] tfidf 分类 阈值
- [x] tfidf + fasttext  音近字替换
- [x] tfidf 更多单词 

- [x] fasttext retest 
- [x] repeat times
- [x] fast text online training  
- [x] 替换方式混合使用
- [ ] 同音字替换限制相同个数
- [x] 插入句号，逗号等方式
- [x] best threshold 
- [ ] 同音字替换方法拆分。如何搞
- [x] 分层替换
- [x] tokenize way
- [x] provided fasttext words
- [x] add text grocery classifier
- [x] merge dirty words in classifiers
- [ ] prediction score of emsenbled classifiers
- [ ] tokenizer cut
- [ ] 繁体字
- [x] delete and append
